// File generated by scripts/pre-build.js

export const commit = "e63f781e73119c4cc7e9ccb62b6c0d47b777e75e";
export const commitShort = "e63f781";
export const commitAuthor = "Fabian Cook";
export const commitEmail = "hello@fabiancook.dev";
export const commitMessage = "group includes type";
export const commitAt = "2023-05-31T11:16:36.000Z";
export const secondsBetweenCommitAndBuild = 81137.15;
export const minutesBetweenCommitAndBuild = 1352.29;
export const timeBetweenCommitAndBuild = "1352 minutes and 17 seconds";
// Variables to be replaced after tests
export const secondsBetweenCommitAndTestCompletion = "81146.16";
export const minutesBetweenCommitAndTestCompletion = "1352.44";
export const timeBetweenCommitAndTestCompletion = "1352 minutes and 26 seconds";