// File generated by scripts/pre-build.js

export const commit = "5f69d059bf95864f9c02564ec752cb9747182b25";
export const commitShort = "5f69d05";
export const commitAuthor = "Fabian Cook";
export const commitEmail = "hello@fabiancook.dev";
export const commitMessage = "Happening page";
export const commitAt = "2023-06-04T01:07:21.000Z";
export const secondsBetweenCommitAndBuild = 502.39;
export const minutesBetweenCommitAndBuild = 8.37;
export const timeBetweenCommitAndBuild = "8 minutes and 22 seconds";
// Variables to be replaced after tests
export const secondsBetweenCommitAndTestCompletion = "";
export const minutesBetweenCommitAndTestCompletion = "";
export const timeBetweenCommitAndTestCompletion = "";